# DATE: 2023-05-15
# AUTHOR: Lucas Pamminger, Tim Peterson and Murray Peel
# VERSION: 1
# FUNCTION: modified_stochastic_rainfall_generator
# Generated rainfall at an annual timescale
# 
# Copied Srikanthan and McMahon 1985 Stochastic Rainfall Generator
# Source: https://ewater.org.au/archive/crcch/archive/pdfs/technical200016.pdf section 2.1
#
# INPUTS
# - parameter_vector:
# ---1 mean: mean of generated rainfall
# ---2 standard_deviation: standard deviation of rainfall
# ---3 autocorrelation: lag-1 autocorrelation of rainfall
# ---4 skew: skewness of rainfall
# - length_of_generated_rainfall: user defined length of generated rainfall vector
#
# OUTPUTS
# - generated_rainfall: rainfall generated by model with mean and sd equal to annual_rainfall_vector
#


modified_stochastic_rainfall_generator <- function(parameter_vector, length_of_generated_rainfall, random){
  
  # ============================================================================
  # Obtain statistical properties of observed rainfall
  #browser() # for debugging
  
  ## Get mean (x_bar) and std (s) of obs. annual rainfall
  x_bar <- parameter_vector[1]
  s <- parameter_vector[2]
  
  ## Get lag-1 autocorrelation coefficent (r) from obs. rainfall
  r <- parameter_vector[3]
    
  ## Get the skewness (gamma) from obs. rainfall
  gamma <- parameter_vector[4]
  
  ## Get coefficient of skewness (gamma_e)
  gamma_e <- ((1 - r^3)  / ((1 - r^2)^(3/2))) * gamma
  
  # ============================================================================
  
  
  # ============================================================================
  # Generating rainfall 
  
  ## This can be toggled to make the sequence of the random numbers is the same for each run.
  if (missing(random)){
    set.seed(8675309) # change back to 8675309
  } else if (random == FALSE){
    set.seed(8675309) # change back to 8675309
  }
  
  eta <- rnorm(length_of_generated_rainfall, mean = 0, sd = 1)
  
  ## Generate random number using eta_t and gamma_e (epsilon)
  epsilon <- (2 / gamma_e) * (((1 + ((gamma_e * eta) / 6) - (gamma_e^2 / 36))^3) - 1)
  
  ## Generate standardised annual rainfall (X)
  X <- numeric(length_of_generated_rainfall)
  X_prev <- 0 # assume X_prev = zero
  
  for (t in 1:length_of_generated_rainfall){
    
    X[t] <- (r * X_prev) + (sqrt(1-(r^2))*epsilon[t])
    X_prev <- X[t]
    
  }
  
  
  ## Annual rainfall amount (generated_rainfall)
  generated_rainfall <- x_bar + (s * X)
  # ============================================================================
  
  return(generated_rainfall)
}








